### ISSUE TITLE
命令行工具的使用文档

### ISSUE THREAD

**Issue by aisensiy** [signcl/openbayes.com#72]

**Comment by sparanoid** [comment]
生成了基本的 CLI 文档信息 https://github.com/signcl/openbayes.com/commit/840316d16e900d9a9555f22a5265d81114f621c9

可能优化的地方：

- 层叠列表内容：目前 CLI 的项目较多
- 制作索引，目前 `docs/cli/` 路径是没有内容的

**Comment by sparanoid** [comment]
基本达到了可以上线的程度
